name = "LinOps"
uuid = "12e01e97-5e40-5c5d-ad16-3cd76309c2d9"
version = "0.1.0"
authors = ["Ferreol Soulez <ferreol.soulez@univ-lyon1.fr>"]

[workspace]
projects = ["test", "docs"]

[deps]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ArrayTools = "1dc0ca97-c5ce-4e77-ac6d-c576ac9d7f27"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
NonuniformFFTs = "cd96f58b-6017-4a02-bb9e-f4d81626177f"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[extensions]
LinOpsCUDAFFTWExt = ["CUDA","FFTW"]
LinOpsFFTWExt = ["FFTW"]
LinOpsNonuniformFFTsExt = ["NonuniformFFTs"]
LinOpsZygoteExt = ["Zygote"]

[compat]
AbstractFFTs = "1"
Adapt = "4"
ArrayTools = "0.3"
CUDA = "5, 6.0"
ChainRulesCore = "1"
FFTW = "1"
KernelAbstractions = "0.9"
LinearAlgebra = "1"
NonuniformFFTs = "0.9"
StaticArrays = "1"
Zygote = "0.7"
julia = "1.10"
